# Generated by Django 5.1.4 on 2025-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_recipe_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeDescription',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
