# Generated by Django 5.1.4 on 2025-01-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_saverecipes_delete_recipecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saverecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='saverecipes',
            name='recipes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='app.recipe'),
        ),
    ]
