# Generated by Django 5.1.4 on 2025-01-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_saverecipes_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saverecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='saverecipes',
            name='recipes',
            field=models.ManyToManyField(to='app.recipe'),
        ),
    ]
