# Generated by Django 5.1.4 on 2025-01-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_saverecipes_recipes_saverecipes_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saverecipes',
            name='recipes',
            field=models.ManyToManyField(related_name='saved_recipes', to='app.recipe'),
        ),
    ]
