# Generated by Django 5.1.4 on 2025-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_saverecipes_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
