# Generated by Django 5.1.4 on 2025-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_recipe_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
